# Generated by Django 3.2.9 on 2022-01-04 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('remaining_leave_days', models.IntegerField(default=21, validators=[django.core.validators.MaxValueValidator(21), django.core.validators.MinValueValidator(0)])),
                ('used_leave_days', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(21), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.AlterField(
            model_name='leave',
            name='days',
            field=models.IntegerField(default=21),
        ),
    ]
